### ISSUE TITLE
Go 왜 하는거에유?

### ISSUE THREAD

**Issue by leechan02** [gitubanana/A-Tour-of-Go#1]
https://youtu.be/LJvEIjRBSDA

**Comment by gitubanana** [comment]
재밌는 영상이네요. ㅋㅋㅋ

**Comment by gitubanana** [comment]
맨날 알고리즘만 풀어서, 새로운 언어 배워보고 싶었어요. ㅋㅋㅋ

**Comment by leechan02** [comment]
아항, 대박이네요. 그럼 혹시 어셈블리는 어떠세용

**Comment by gitubanana** [comment]
나중에 배워야죵.

**Comment by gitubanana** [comment]
의찬님은 웹 어셈블리 하세요. ㅋㅋㅋ

**Comment by leechan02** [comment]
웹 어셈블리도... 있어요...? 와웅...

**Comment by leechan02** [comment]
오늘 TMI 하나 알려드릴까요? api 로직 잘못 짜서 무한호출 비슷한거 걸린 덕분에 5분만에 하루 api 호출 제한량 넘었어요^^

**Comment by gitubanana** [comment]
재밌는 경험이네요. ㅋㅋㅋ
